# this is the build file for project ivp
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CU=/usr/bin/clang
CXX=/usr/bin/gcc
AS=/usr/bin/gcc
MM=/usr/bin/gcc
MXX=/usr/bin/gcc
FC=/usr/bin/gfortran
CC=/usr/bin/gcc

FCLD=/usr/bin/gfortran
LD=/usr/bin/g++
FCSH=/usr/bin/gfortran
SH=/usr/bin/g++
AR=/usr/bin/ar

test_LD=/usr/bin/g++
test_CXX=/usr/bin/gcc
test_CXX=/usr/bin/gcc
ivp_AR=/usr/bin/ar
ivp_CXX=/usr/bin/gcc
ivp_CXX=/usr/bin/gcc

test_CXXFLAGS=-m64 -std=c++17 -Iinclude
test_CXXFLAGS=-m64 -std=c++17 -Iinclude
test_LDFLAGS=-m64 -Llib -livp
ivp_CXXFLAGS=-m64 -std=c++17 -Iinclude
ivp_CXXFLAGS=-m64 -std=c++17 -Iinclude
ivp_ARFLAGS=-cr

default:  test all clean plot ivp report

all:  test all clean plot ivp report

.PHONY: default all  test all clean plot ivp report

test: bin/test
bin/test: lib/libivp.a build/.objs/test/linux/x86_64/release/test/test.cpp.o
	@echo linking.release test
	@mkdir -p bin
	$(VV)$(test_LD) -o bin/test build/.objs/test/linux/x86_64/release/test/test.cpp.o $(test_LDFLAGS)

build/.objs/test/linux/x86_64/release/test/test.cpp.o: test/test.cpp
	@echo compiling.release test/test.cpp
	@mkdir -p build/.objs/test/linux/x86_64/release/test
	$(VV)$(test_CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/release/test/test.cpp.o test/test.cpp

all: ivp test report
clean:
plot:
ivp: lib/libivp.a
lib/libivp.a: build/.objs/ivp/linux/x86_64/release/src/Adams_Bashforth_Methods.cpp.o build/.objs/ivp/linux/x86_64/release/src/Adams_Moulton_Methods.cpp.o build/.objs/ivp/linux/x86_64/release/src/Backward_Differentiation_Formula.cpp.o build/.objs/ivp/linux/x86_64/release/src/ClassicalRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/Dormand_PrinceRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/ESDIRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/Euler_Method.cpp.o build/.objs/ivp/linux/x86_64/release/src/FehlbergRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/GLRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/story.cpp.o build/.objs/ivp/linux/x86_64/release/src/TimeIntegrator.cpp.o build/.objs/ivp/linux/x86_64/release/src/UnitTimer.cpp.o build/.objs/ivp/linux/x86_64/release/src/VectorFunction.cpp.o
	@echo linking.release libivp.a
	@mkdir -p lib
	$(VV)$(ivp_AR) $(ivp_ARFLAGS) lib/libivp.a build/.objs/ivp/linux/x86_64/release/src/Adams_Bashforth_Methods.cpp.o build/.objs/ivp/linux/x86_64/release/src/Adams_Moulton_Methods.cpp.o build/.objs/ivp/linux/x86_64/release/src/Backward_Differentiation_Formula.cpp.o build/.objs/ivp/linux/x86_64/release/src/ClassicalRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/Dormand_PrinceRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/ESDIRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/Euler_Method.cpp.o build/.objs/ivp/linux/x86_64/release/src/FehlbergRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/GLRK.cpp.o build/.objs/ivp/linux/x86_64/release/src/story.cpp.o build/.objs/ivp/linux/x86_64/release/src/TimeIntegrator.cpp.o build/.objs/ivp/linux/x86_64/release/src/UnitTimer.cpp.o build/.objs/ivp/linux/x86_64/release/src/VectorFunction.cpp.o

build/.objs/ivp/linux/x86_64/release/src/Adams_Bashforth_Methods.cpp.o: src/Adams_Bashforth_Methods.cpp
	@echo compiling.release src/Adams_Bashforth_Methods.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/Adams_Bashforth_Methods.cpp.o src/Adams_Bashforth_Methods.cpp

build/.objs/ivp/linux/x86_64/release/src/Adams_Moulton_Methods.cpp.o: src/Adams_Moulton_Methods.cpp
	@echo compiling.release src/Adams_Moulton_Methods.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/Adams_Moulton_Methods.cpp.o src/Adams_Moulton_Methods.cpp

build/.objs/ivp/linux/x86_64/release/src/Backward_Differentiation_Formula.cpp.o: src/Backward_Differentiation_Formula.cpp
	@echo compiling.release src/Backward_Differentiation_Formula.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/Backward_Differentiation_Formula.cpp.o src/Backward_Differentiation_Formula.cpp

build/.objs/ivp/linux/x86_64/release/src/ClassicalRK.cpp.o: src/ClassicalRK.cpp
	@echo compiling.release src/ClassicalRK.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/ClassicalRK.cpp.o src/ClassicalRK.cpp

build/.objs/ivp/linux/x86_64/release/src/Dormand_PrinceRK.cpp.o: src/Dormand_PrinceRK.cpp
	@echo compiling.release src/Dormand_PrinceRK.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/Dormand_PrinceRK.cpp.o src/Dormand_PrinceRK.cpp

build/.objs/ivp/linux/x86_64/release/src/ESDIRK.cpp.o: src/ESDIRK.cpp
	@echo compiling.release src/ESDIRK.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/ESDIRK.cpp.o src/ESDIRK.cpp

build/.objs/ivp/linux/x86_64/release/src/Euler_Method.cpp.o: src/Euler_Method.cpp
	@echo compiling.release src/Euler_Method.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/Euler_Method.cpp.o src/Euler_Method.cpp

build/.objs/ivp/linux/x86_64/release/src/FehlbergRK.cpp.o: src/FehlbergRK.cpp
	@echo compiling.release src/FehlbergRK.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/FehlbergRK.cpp.o src/FehlbergRK.cpp

build/.objs/ivp/linux/x86_64/release/src/GLRK.cpp.o: src/GLRK.cpp
	@echo compiling.release src/GLRK.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/GLRK.cpp.o src/GLRK.cpp

build/.objs/ivp/linux/x86_64/release/src/story.cpp.o: src/story.cpp
	@echo compiling.release src/story.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/story.cpp.o src/story.cpp

build/.objs/ivp/linux/x86_64/release/src/TimeIntegrator.cpp.o: src/TimeIntegrator.cpp
	@echo compiling.release src/TimeIntegrator.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/TimeIntegrator.cpp.o src/TimeIntegrator.cpp

build/.objs/ivp/linux/x86_64/release/src/UnitTimer.cpp.o: src/UnitTimer.cpp
	@echo compiling.release src/UnitTimer.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/UnitTimer.cpp.o src/UnitTimer.cpp

build/.objs/ivp/linux/x86_64/release/src/VectorFunction.cpp.o: src/VectorFunction.cpp
	@echo compiling.release src/VectorFunction.cpp
	@mkdir -p build/.objs/ivp/linux/x86_64/release/src
	$(VV)$(ivp_CXX) -c $(ivp_CXXFLAGS) -o build/.objs/ivp/linux/x86_64/release/src/VectorFunction.cpp.o src/VectorFunction.cpp

